name: questions
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # Bloc for state management
  flutter_bloc: ^8.1.2
  # Functional programming things
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.5
  # Service locator
  get_it: ^7.6.0
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.5
  # Local cache
  shared_preferences: ^2.1.1
  #responsive screen utils
  flutter_screenutil:

#  firebase
  cloud_firestore: ^4.9.2
  firebase_core: ^2.16.0
  google_sign_in: ^6.1.4
  firebase_auth: ^4.10.0
  onesignal_flutter: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
